[dev]
command = "netlify dev"
framework = "#custom"
port = 8888
targetPort = 3000
autoLaunch = true

[functions]
directory = "functions/"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

